---

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  - 'user-data'

rules:
  comments:
    level: warning
    ignore: user-data
    min-spaces-from-content: 1
  document-start:
    ignore: |
      /**/vault*
      user-data
  line-length:
    max: 120
    ignore: |
      /.github/

ignore: |
  .vagrant
  .venv
