---

- name: Create Splunk user
  ansible.builtin.user:
    name: splunk
    password: "!"
    password_lock: true
    shell: /bin/false

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Get the installed version of Splunk Forwarder
  ansible.builtin.set_fact:
    splunk_installed_version: "{{ ansible_facts.packages['splunkforwarder']['version'] | default(None) }}"

- name: Download Splunk universal forwarder
  register: splunk_download
  when: "splunk_installed_version != splunk_version"
  ansible.builtin.get_url:
    url: "https://{{ s3_config_bucket }}.s3.amazonaws.com/{{ s3_package_prefix }}/{{ splunk_deb }}"
    dest: "/home/splunk/{{ splunk_deb }}"
    mode: '0644'
    checksum: "sha256:21fdd8c5af99f47fa8a2a7a1c2771491371fbf3bb83c854c9b82b55caf0e1588"

- name: Install Splunk universal forwarder
  when: splunk_download.changed  # noqa: no-handler
  register: splunk_install
  ansible.builtin.apt:
    deb: "/home/splunk/{{ splunk_deb }}"
    allow_downgrade: "yes"

- name: Generate local Splunk admin password
  ansible.builtin.shell:
    creates: /root/.splunk_admin_password
    cmd: python3 -c "import secrets; print(secrets.token_urlsafe())" > /root/.splunk_admin_password

- name: Initialize Splunk
  ansible.builtin.shell:
    cmd: >-
      /opt/splunkforwarder/bin/splunk start
      --accept-license
      --answer-yes
      --no-prompt
      --seed-passwd $(cat /root/.splunk_admin_password)
    creates: /opt/splunkforwarder/var/run/splunk/splunkd.pid

- name: Configure Splunk inputs
  ansible.builtin.template:
    owner: splunk
    group: splunk
    src: inputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
    mode: '0600'
  notify: Splunk

- name: Verify SSL certificates
  ansible.builtin.lineinfile:
    path: /opt/splunkforwarder/etc/splunk-launch.conf
    regexp: "^PYTHONHTTPSVERIFY=0"
    line: "PYTHONHTTPSVERIFY=1"
  notify: Splunk

- name: Only bind to localhost
  ansible.builtin.lineinfile:
    path: /opt/splunkforwarder/etc/splunk-launch.conf
    insertafter: EOF
    line: "SPLUNK_BINDIP=127.0.0.1"
  notify: Splunk

- name: Generate SSL certificate for localhost
  become: true
  become_user: splunk
  ansible.builtin.command:
    creates: /opt/splunkforwarder/etc/auth/localhost.pem
    cmd: >-
      /opt/splunkforwarder/bin/splunk createssl server-cert
      -d /opt/splunkforwarder/etc/auth
      -n localhost
      -c localhost
  notify: Splunk

- name: Remove Splunk Forwarder package after installation
  when: splunk_install.changed  # noqa: no-handler
  ansible.builtin.file:
    name: "/home/splunk/{{ splunk_deb }}"
    state: absent
