---

# deleted users
users_deleted:
  - username: ubuntu  # delete default user
  - username: kjohnson  # typo
  - username: hlingutla
  - username: ctzunuxpineda
  - username: pkim
  - username: cmaddox
  - username: wjohnson
