---
- name: create Splunk user
  user:
    name: splunk
    password: "!"
    password_lock: true
    shell: /bin/false
- name: download Splunk universal forwarder
  get_url:
    checksum: "{{ splunk_deb_checksum }}"
    dest: "/home/splunk/{{ splunk_deb }}"
    url: "https://download.splunk_com/products/universalforwarder/releases/{{ splunk_version }}/linux/{{ splunk_deb }}"
- name: Install Splunk universal forwarder
  apt:
    deb: "/home/splunk/{{ splunk_deb }}"
- name: Generate local Splunk admin password
  shell:
    creates: /root/.splunk_admin_password
    cmd: python3 -c "import secrets; print(secrets.token_urlsafe())" > /root/.splunk_admin_password
- name: Initialize Splunk
  shell:
    cmd: /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd $(cat /root/.splunk_admin_password)
    creates: /opt/splunkforwarder/var/run/splunk/splunkd.pid
- name: Copy Splunkcloud configuration
  copy:
    owner: splunk
    group: splunk
    src: files/splunkclouduf.spl
    dest: /opt/splunkforwarder/etc/deployment-apps/splunkclouduf.spl
- name: Expand Splunkcloud configuration
  unarchive:
    owner: splunk
    group: splunk
    src: /opt/splunkforwarder/etc/deployment-apps/splunkclouduf.spl
    dest: /opt/splunkforwarder/etc/deployment-apps
- name: Add Splunkcloud configuration to Splunk
  shell:
    creates: /opt/splunkforwarder/etc/apps/100_mbta_splunkcloud
    cmd: /opt/splunkforwarder/bin/splunk install app /opt/splunkforwarder/etc/deployment-apps/splunkclouduf.spl  -auth admin:$(cat /root/.splunk_admin_password)
  notify: splunk
- name: Configure Splunk inputs
  template:
    owner: splunk
    group: splunk
    src: inputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
  notify: splunk
- name: Verify SSL certificates
  lineinfile:
    path: /opt/splunkforwarder/etc/splunk-launch.conf
    regexp: "^PYTHONHTTPSVERIFY=0"
    line: "PYTHONHTTPSVERIFY=1"
  notify: splunk
