---

- name: Configure kiosk system settings
  ansible.builtin.include_tasks: system.yml

- name: Configure Firefox
  ansible.builtin.include_tasks: firefox.yml

- name: Configure debugging
  ansible.builtin.include_tasks: debug.yml

# TODO:
# - Fix user lists across all groups
# - Fix "admin" vs. "sudo" groups
