---

- name: Ensure required packages for AWSCLI are installed
  ansible.builtin.apt:
    name:
      - ca-certificates
      - cron
      - python3-pip
      - unzip
    state: present

- name: Boto3 package is installed
  ansible.builtin.pip:
    name: boto3

- name: Fetch CLI install script
  ansible.builtin.get_url:
    dest: /root/awscliv2.zip
    owner: root
    group: root
    mode: '0600'
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  register: ecs_anywhere_cli_zip

- name: Expand AWSCLI
  when: ecs_anywhere_cli_zip.changed  # noqa: no-handler
  ansible.builtin.unarchive:
    src: /root/awscliv2.zip
    dest: /root
    remote_src: true

- name: Install AWSCLI
  when: ecs_anywhere_cli_zip.changed  # noqa: no-handler
  register: ecs_anywhere_cli_installed
  changed_when: true
  ansible.builtin.command:
    /root/aws/install --bin-dir /usr/local/bin --update

- name: Clean up expanded archive
  ansible.builtin.file:
    path: /root/aws
    state: absent

- name: Configure a cronjob to expire old versions of the CLI (excluding the current version)
  ansible.builtin.cron:
    name: aws-cli-expire
    user: root
    special_time: "weekly"
    job: >-
      find /usr/local/aws-cli/v2
      -maxdepth 1 -type d -mtime +30
      -not \( -wholename $(realpath /usr/local/aws-cli/v2/current) \)
      -exec rm -r '{}' \;
      | /usr/bin/logger -t aws-cli-expire --id="${PPID}" -S 4096
