---

- name: Install Docker
  ansible.builtin.include_role:
    name: docker

- name: Apparmor profile for Docker
  ansible.builtin.copy:
    src: files/docker-default
    dest: /etc/apparmor.d/docker-default
    owner: root
    group: root
    mode: "0644"
  notify:
    - Apparmor for Docker
    - Docker
    - ECS agent
