---

- name: Install libpam-google-authenticator
  ansible.builtin.apt:
    name: libpam-google-authenticator
    state: present

- name: Require Google Authenticator configuration on login
  ansible.builtin.copy:
    src: files/google-authenticator.sh
    dest: /usr/local/sbin/enforce-google-authenticator
    owner: root
    group: root
    mode: '0755'

- name: (sudo) Require google authenticator
  ansible.builtin.blockinfile:
    path: /etc/pam.d/sudo
    marker: "# {mark} Google Authenticator"
    state: absent
    insertafter: EOF
    block: |
      auth required pam_google_authenticator.so

- name: (sudo) Disable normal auth
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sudo
    regexp: '^@include common-auth'
    line: "#@include common-auth"
    state: absent

- name: (ssh) Disable password auth
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication yes'
    line: "PasswordAuthentication no"
    state: present
  notify: SSH

- name: (ssh) Require google authenticator (if configured)
  ansible.builtin.blockinfile:
    path: /etc/pam.d/sshd
    marker: "# {mark} Google Authenticator"
    state: present
    insertafter: EOF
    block: |
      auth required pam_google_authenticator.so nullok
      auth required pam_permit.so
  notify: SSH

- name: (ssh) Disable normal auth
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sshd
    regexp: '^@include common-auth'
    line: "#@include common-auth"
    state: present
  notify: SSH

- name: (ssh) Enable keyboard-interactive authentication
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/50-google-authenticator.conf
    owner: root
    group: root
    mode: '0644'
    content: |
     ForceCommand /usr/local/sbin/enforce-google-authenticator
     AuthenticationMethods publickey,keyboard-interactive
     ChallengeResponseAuthentication yes
  notify: SSH
