---
- name: Ensure cron is present
  apt:
    name: cron
- name: Run ansible-pull every 15m
  cron:
    name: ansible-pull
    user: root
    job: "ansible-pull -C {{ git_branch }} -U https://github.com/{{ github_repo }}.git --vault-password-file /root/.ansible_vault_password -i linux/inventory.yml --extra-vars \"github_repo={{ github_repo }} git_branch={{ git_branch }}\" linux/main.yml"
    minute: "*/15"
