---
- name: Ensure cron is present
  apt:
    name: cron
- name: Run ansible-pull every 15m
  cron:
    name: ansible-pull
    user: root
    job: "ansible-pull -C linux -U https://github.com/paulswartz/on_prem_deploy.git  --vault-password-file /root/.ansible_vault_password linux/main.yml"
    minute: "*/15"
