---
- name: Install libpam-google-authenticator
  apt:
    name: libpam-google-authenticator
    state: present
- name: Require Google Authenticator configuration on login
  copy:
    dest: /etc/profile.d/google-authenticator.sh
    owner: root
    group: root
    mode: '0755'
    content: |
      if [ ! -f $HOME/.google_authenticator ]; then
        google-authenticator -tDW -r 3 -R 30
      fi
      if [ ! -f $HOME/.google_authenticator ]; then
        exit 1
      fi
- name: (sudo) Require google authenticator
  blockinfile:
    path: /etc/pam.d/sudo
    marker: "# {mark} Google Authenticator"
    state: present
    insertafter: EOF
    block: |
      auth required pam_google_authenticator.so
- name: (sudo) Disable normal auth
  lineinfile:
    path: /etc/pam.d/sudo
    regexp: '^@include common-auth'
    line: "#@include common-auth"
    state: present
- name: (ssh) Disable password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication yes'
    line: "PasswordAuthentication no"
    state: present
  notify: ssh
- name: (ssh) Require google authenticator (if configured)
  blockinfile:
    path: /etc/pam.d/sshd
    marker: "# {mark} Google Authenticator"
    state: present
    insertafter: EOF
    block: |
      auth required pam_google_authenticator.so nullok
      auth required pam_permit.so
  notify: ssh
- name: (ssh) Disable normal auth
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '^@include common-auth'
    line: "#@include common-auth"
    state: present
  notify: ssh
- name: (ssh) Enable keyboard-interactive authentication
  copy:
    dest: /etc/ssh/sshd_config.d/50-google-authenticator.conf
    owner: root
    group: root
    mode: '0644'
    content: |
     AuthenticationMethods publickey,keyboard-interactive
     ChallengeResponseAuthentication yes
  notify: ssh
