---
- name: Create docker group
  ansible.builtin.group:
    name: docker
- name: Create devops users
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.comment }}"
    password: "!"
    password_lock: true
    groups:
      - admin
      - users
      - docker
    shell: /bin/bash
    append: false
  loop: "{{ devops_users + itd_users }}"
- name: Copy user's ssh key
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    key: "https://github.com/{{ item.github }}.keys"
  become: true
  loop: "{{ devops_users + itd_users }}"
- name: Users in admin group do not need passwords
  ansible.builtin.copy:
    dest: /etc/sudoers.d/mbta-admins
    owner: root
    group: root
    mode: '0440'
    content: |
      %admin ALL=(ALL) NOPASSWD:ALL
- name: Delete default `ubuntu` user
  ansible.builtin.user:
    name: ubuntu
    state: absent
