---

- name: Ensure old Docker packages are not installed
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: /etc/apt/keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: GPG key for Docker
  ansible.builtin.copy:
    src: docker.gpg
    dest: /etc/apt/keyrings/docker.gpg
    owner: root
    group: root
    mode: "0644"

- name: Generate docker.list output
  register: docker_list
  ansible.builtin.shell:
    cmd: >-
      echo deb [arch=$(dpkg --print-architecture)
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu
      $(. /etc/os-release && echo "$VERSION_CODENAME")
      stable
  changed_when: false

- name: Add Docker repo to apt
  ansible.builtin.apt_repository:
    repo: "{{ docker_list.stdout }}"
    filename: docker

- name: Ensure new Docker packages are installed
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Prune resources weekly
  ansible.builtin.include_tasks:
    file: prune-docker.yml
