---
- name: Create docker group
  ansible.builtin.group:
    name: docker
- name: Create devops users
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.comment }}"
    password: "!"
    password_lock: true
    groups:
      - admin
      - users
      - docker
    shell: /bin/bash
    append: false
  loop: "{{ users_devops + users_itd }}"
- name: Create paess users
  when: ansible_hostname == 'PPCTDSCUTST01'
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.comment }}"
    password: "!"
    password_lock: true
    groups:
      - users
      - docker
    shell: /bin/bash
    append: false
  loop: "{{ paess_users }}"
- name: Copy user's ssh key
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    key: "https://github.com/{{ item.github }}.keys"
  become: true
  loop: "{{ users_devops + users_itd + users_paess }}"
  when: item.github
- name: Users in admin group do not need passwords
  ansible.builtin.copy:
    dest: /etc/sudoers.d/mbta-admins
    owner: root
    group: root
    mode: '0440'
    content: |
      %admin ALL=(ALL) NOPASSWD:ALL
- name: Delete users who should no longer have access
  ansible.builtin.user:
    name: "{{ item.username }}"
    state: absent
  loop: "{{ onprem_deleted_users }}"
