---

devops_users:
  - username: pswartz
    comment: Paul Swartz
    github: paulswartz
  - username: iwestcott
    comment: Ian Westcott
    github: ianwestcott
  - username: kjohnson
    comment: Kris Johnson
    github: krisrjohnson21

itd_users:
  - username: ctzunuxpineda
    comment: Carlos Tzunux-Pineda
    github: carlostpineda
  - username: rkuthuru
    comment: Raj Kuthuru
    github: rkuthuru12
