---

- name: SSH
  ansible.builtin.service:
    name: ssh
    state: reloaded
- name: Toggle NTP
  changed_when: true
  ansible.builtin.shell: |
    timedatectl set-ntp false
    timedatectl set-ntp true
