---
- name: Download Nessus
  register: tenable_download
  amazon.aws.s3_object:
    region: "{{ s3_config_region }}"
    bucket: "{{ s3_config_bucket }}"
    object: "{{ s3_config_prefix }}/{{ tenable_path }}"
    dest: /root/nessus.deb
    mode: get
    overwrite: different
    ignore_nonexistent_bucket: true
- name: Install Nessus
  when: tenable_download.changed # noqa: no-handler
  register: tenable_install
  ansible.builtin.apt:
    deb: /root/nessus.deb
- name: Configure Nessus
  when: tenable_install.changed # noqa: no-handler
  changed_when: false
  ansible.builtin.command: >-
    /opt/nessus_agent/sbin/nessuscli agent link
    --key={{ tenable_key | trim | quote }}
    --groups={{ tenable_groups | quote }}
    --host={{ tenable_host }}
    --port={{ tenable_port }}
