---

- name: Stop Nessus Agent service
  ansible.builtin.service:
    name: nessusagent
    state: stopped

- name: Uninstall Nessus Agent package
  ansible.builtin.apt:
    name: nessusagent
    state: absent

- name: Remove Nessus Agent configuration and data directories
  ansible.builtin.file:
    state: absent
    path: /opt/nessus_agent
