---
- name: Download Nessus
  register: download_nessus
  get_url:
    dest: /root/nessus.deb
    checksum: "{{ tenable_checksum }}"
    url: "{{ tenable_url }}"
- name: Install Nessus
  when: download_nessus.changed
  register: install_nessus
  apt:
    deb: /root/nessus.deb
- name: Configure Nessus
  when: install_nessus.changed
  shell:
    cmd: |
      /opt/nessus_agent/sbin/nessuscli agent link \
      --key={{ tenable_key | trim | quote }} \
      --groups={{ tenable_groups | quote }} \
      --host={{ tenable_host }} \
      --port={{ tenable_port }}
