---
- name: Download Nessus
  register: download_nessus
  aws_s3:
    region: "{{ s3_config_region }}"
    bucket: "{{ s3_config_bucket }}"
    object: "{{ s3_config_prefix | trim }}/{{ tenable_path }}"
    dest: /root/nessus.deb
    mode: get
    overwrite: different
    ignore_nonexistent_bucket: true
- name: Install Nessus
  when: download_nessus.changed
  register: install_nessus
  apt:
    deb: /root/nessus.deb
- name: Configure Nessus
  when: install_nessus.changed
  shell:
    cmd: |
      /opt/nessus_agent/sbin/nessuscli agent link \
      --key={{ tenable_key | trim | quote }} \
      --groups={{ tenable_groups | quote }} \
      --host={{ tenable_host }} \
      --port={{ tenable_port }}
