---
- hosts: all
  connection: local
  become: true
  roles:
    - onprem
  vars:
    github_repo: mbta/on_prem_deploy
    git_branch: main
- hosts: full
  roles:
    - splunk
    - ecs-anywhere
    - crowdstrike
    - tenable
