---

- name: All hosts
  hosts: all
  become: true
  roles:
    - role: ansible
      tags: [initial]

- name: CI
  hosts: ci
  roles:
    - role: onprem
      tags: [initial]

- name: Local development
  hosts: local
  roles:
    - role: pull
      tags: [pull]
    - role: users
      tags: [users]
    - role: onprem
      tags: [initial]
    - role: ecs_anywhere
      tags: [ecs_anywhere]
    - role: splunk
      tags: [splunk]
    - role: metrics
      tags: [metrics]
    - role: crowdstrike
      tags: [crowdstrike]
    - role: tenable
      tags: [tenable]

- name: Staging environment
  hosts: staging
  vars:
    splunk_index: onprem-linux-staging
    ecs_anywhere_region: us-east-1
    ecs_anywhere_cluster: linux-staging
  roles:
    - role: pull
    - role: users
    - role: onprem
      tags: [initial]
    - role: ecs_anywhere
    - role: splunk
    - role: metrics
    - role: crowdstrike
    - role: tenable

- name: PA/ESS Testing
  hosts: paess_testing
  roles:
    - role: pull
    - role: users
    - role: crowdstrike
    - role: tenable

- name: Screens for realtime arrival info
  hosts: arrival_screen
  vars:
    # TODO remove these overrides to enable registration
    ecs_anywhere_activate: false
    crowdstrike_configure_falcon_sensor: false
    splunk_enable_forwarding: false
    tenable_link_nessus_agent: false
  roles:
    - role: pull
    - role: users
    - role: onprem
      tags: [initial]
    # TODO decide whether to send logs to Splunk
    # - role: splunk
    - role: crowdstrike
    - role: tenable
    - role: kiosk

- name: Production environment
  hosts: prod
  vars:
    splunk_index: onprem-linux-prod
    ecs_anywhere_region: us-east-1
    ecs_anywhere_cluster: linux-prod
  roles:
    - role: pull
    - role: users
    - role: onprem
      tags: [initial]
    - role: ecs_anywhere
    - role: splunk
    - role: metrics
    - role: crowdstrike
    - role: tenable
