---
- name: All hosts
  hosts: all
  connection: local
  become: true
  roles:
    - role: onprem
      tags: [initial]
  vars:
    github_repo: mbta/on_prem_deploy
    git_branch: main
- name: Local development
  hosts: local
  roles:
    - ecs_anywhere
    - splunk
    - crowdstrike
    - tenable
- name: Staging environment
  hosts: staging
  vars:
    splunk_index: onprem-linux-staging
    ecs_anywhere_region: us-east-1
    ecs_anywhere_cluster: linux-staging
  roles:
    - ecs_anywhere
    - splunk
    - crowdstrike
    - tenable
- name: Production environment
  hosts: prod
  vars:
    splunk_index: onprem-linux-prod
    ecs_anywhere_region: us-east-1
    ecs_anywhere_cluster: linux-prod
  roles:
    - ecs_anywhere
    - splunk
    - crowdstrike
    - tenable
