---

- name: All hosts
  hosts: all
  become: true
  roles:
    - role: ansible
      tags: [initial]

- name: CI
  hosts: ci
  roles:
    - role: onprem
      tags: [initial]

- name: Local development
  hosts: local
  roles:
    - role: pull
      tags: [pull]
    - role: users
      tags: [users]
    - role: onprem
      tags: [initial]
    - role: ecs_anywhere
      tags: [ecs_anywhere]
    - role: splunk
      tags: [splunk]
    - role: metrics
      tags: [metrics]
    - role: crowdstrike
      tags: [crowdstrike]
    - role: qualys
      tags: [qualys]

- name: Staging environment
  hosts: staging
  vars:
    splunk_index: onprem-linux-staging
    ecs_anywhere_region: us-east-1
    ecs_anywhere_cluster: linux-staging
  roles:
    - role: pull
    - role: users
    - role: onprem
      tags: [initial]
    - role: ecs_anywhere
    - role: splunk
    - role: metrics
    - role: crowdstrike
    - role: qualys
      tags: [qualys]

- name: Station Control Unit
  hosts: scu
  vars:
    aws_region: us-east-1
  roles:
    - role: pull
    - role: users
    - role: crowdstrike
      tags: [crowdstrike]
    - role: qualys
      tags: [qualys]
    - role: scu

- name: Screens for realtime arrival info
  hosts: arrival_screen
  roles:
    - role: pull
    - role: users
    - role: onprem
      tags: [initial]
    # TODO decide whether to send logs to Splunk
    # - role: splunk
    - role: crowdstrike
    - role: qualys
    - role: kiosk

- name: Production environment
  hosts: prod
  vars:
    splunk_index: onprem-linux-prod
    ecs_anywhere_region: us-east-1
    ecs_anywhere_cluster: linux-prod
  roles:
    - role: pull
    - role: users
    - role: onprem
      tags: [initial]
    - role: ecs_anywhere
    - role: splunk
    - role: metrics
    - role: crowdstrike
    - role: qualys

- name: Bastion host
  hosts: bastion_host
  roles:
    - role: pull
    - role: users
    - role: onprem
      tags: [initial]
    - role: splunk
    - role: crowdstrike
    - role: qualys
    - role: bastion_host

- name: Splunk base image
  hosts: splunk_base_image
  roles:
    - role: pull
    - role: users
    - role: onprem
      tags: [initial]
    - role: crowdstrike
    - role: qualys
