---
- name: All hosts
  hosts: all
  become: true
- name: Local development
  hosts: local
  roles:
    - role: onprem
      tags: [initial]
    - role: ecs_anywhere
      tags: [ecs_anywhere]
    - role: splunk
      tags: [splunk]
    - role: crowdstrike
      tags: [crowdstrike]
    - role: tenable
      tags: [tenable]
- name: Staging environment
  hosts: staging
  vars:
    splunk_index: onprem-linux-staging
    ecs_anywhere_region: us-east-1
    ecs_anywhere_cluster: linux-staging
  roles:
    - role: onprem
      tags: [initial]
    - role: ecs_anywhere
    - role: splunk
    - role: crowdstrike
    - role: tenable
- name: Production environment
  hosts: prod
  vars:
    splunk_index: onprem-linux-prod
    ecs_anywhere_region: us-east-1
    ecs_anywhere_cluster: linux-prod
  roles:
    - role: onprem
      tags: [initial]
    - role: ecs_anywhere
    - role: splunk
    - role: crowdstrike
    - role: tenable
