---
- hosts: all
  connection: local
  become: true
  roles:
    - onprem
  vars:
    github_repo: mbta/on_prem_deploy
    git_branch: main
- hosts: vagrant
  roles:
    - splunk
    - ecs-anywhere
    - crowdstrike
    - tenable
- hosts: staging
  vars:
    splunk:
      index: onprem-linux-staging
    ecs_anywhere:
      region: us-east-1
      cluster: linux-staging
      activation_id: TBD
      activation_code: TBD
  roles:
    - splunk
    - ecs-anywhere
    - crowdstrike
    - tenable
