# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  vm_name = ENV["VAGRANT_HOSTNAME"] || "vagrant"
  github_repo = ENV["GITHUB_REPO"] || "mbta/on_prem_deploy"
  git_branch = ENV["GIT_BRANCH"] || "main"
  ansible_vault_password = ENV["ANSIBLE_VAULT_PASSWORD"] || File.read(".ansible_vault_password")

  config.vagrant.plugins = ["vagrant-env", "vagrant-vbguest"]
  config.env.enable # enable .env support plugin (it will let us easily enable cloud_init support)
  config.vbguest.auto_update = false

  config.vm.box = "ubuntu/jammy64"

  config.vm.define vm_name

  config.vm.hostname = vm_name

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.name = vm_name

    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  # disable folder syncing
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.cloud_init :user_data do |cloud_init|
    cloud_init.content_type = "text/cloud-config"
    user_data = File.read("cloud-init/user-data")
                          .gsub("GITHUB_REPO", github_repo)
                          .gsub("GIT_BRANCH", git_branch)
                          .gsub("ANSIBLE_VAULT_PASSWORD", ansible_vault_password)
    cloud_init.inline = <<-EOF
#cloud-config
hostname: #{vm_name}

#{user_data}
EOF
  end
end
