# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  vm_name = "onprem-linux"

  config.vagrant.plugins = "vagrant-env" # Install plugin to support .env files
  config.env.enable # enable .env support plugin (it will let us easily enable cloud_init support)

  config.vm.box = "ubuntu/jammy64"

  config.vm.define vm_name

  config.vm.hostname = vm_name

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.name = vm_name

    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  # disable folder syncing
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.cloud_init :user_data do |cloud_init|
    cloud_init.content_type = "text/cloud-config"
    cloud_init.inline = <<-EOF
#cloud-config
hostname: #{vm_name}
write_files:
  - path: /root/.ansible_vault_password
    mode: '0400'
    content: #{ENV["ANSIBLE_VAULT_PASSWORD"] || File.read(".ansible_vault_password")}
EOF
  end

  config.vm.cloud_init :user_data do |cloud_init|
    cloud_init.content_type = "text/cloud-config"
    cloud_init.path = "cloud-init/user-data"
  end
end
