---

splunk_enable_forwarding: true
splunk_version: "9.3.0"
splunk_deb: "splunkforwarder-{{ splunk_version }}-51ccf43db5bd-linux-2.6-amd64.deb"
splunk_index: test
splunk_forwarder_collectd_https_port: 9556  # randomly generated
splunk_forwarder_collectd_index: collectd-metrics
