name: Build Erlang/Elixir images

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - build_erlang_container.ps1
      - build_elixir_container.ps1
      - docker/**

env:
  REGISTRY: ghcr.io

jobs:
  erlang2019:
    name: Erlang images
    continue-on-error: true
    strategy:
      # Supported Erlang versions: search for `otp_win64` in
      # https://erlang.org/download/
      matrix:
        include:
          - erlang_version: "26.0"
            windows_version: 1809
          - erlang_version: 25.3.2.2
            windows_version: 1809
          - erlang_version: 25.2.3
            windows_version: 1809
          - erlang_version: 25.1.2
            windows_version: 1809
          - erlang_version: 25.0.4
            windows_version: 1809
          - erlang_version: 24.3.4.12
            windows_version: 1809
          - erlang_version: 23.3.4.18
            windows_version: 1809
          - erlang_version: 22.3
            windows_version: 1809
    runs-on: windows-2019
    permissions:
      contents: read
      packages: write
    steps:
      - name: Force build if workflow_dispatch or re-run
        id: force
        if: github.event_name == 'workflow_dispatch' || github.run_attempt != '1'
        run: echo "force=-Force" >> $env:GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build Erlang tag for Docker Hub (if needed)
        run: ./build_erlang_container.ps1 -ImageNameRoot ${{ secrets.DOCKER_USERNAME }}/windows- -WindowsVersion ${{ matrix.windows_version }} -ErlangVersion ${{ matrix.erlang_version }} ${{ steps.force.outputs.force }}
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Erlang tag for GHCR (if needed)
        run: ./build_erlang_container.ps1 -ImageNameRoot ${{ env.REGISTRY }}/${{ github.repository_owner }}/windows- -WindowsVersion ${{ matrix.windows_version }} -ErlangVersion ${{ matrix.erlang_version }} ${{ steps.force.outputs.force }}

  elixir2019:
    name: Elixir images
    continue-on-error: true
    needs: erlang2019
    strategy:
      # Elixir compatibility matrix:
      # https://hexdocs.pm/elixir/1.14.0/compatibility-and-deprecations.html
      matrix:
        include:
          # Elixir 1.14
          - elixir_version: 1.14.5
            erlang_version: 25.3.2.2
            windows_version: 1809
          - elixir_version: 1.14.5
            erlang_version: 25.2.3
            windows_version: 1809
          - elixir_version: 1.14.5
            erlang_version: 25.1.2
            windows_version: 1809
          - elixir_version: 1.14.5
            erlang_version: 25.0.4
            windows_version: 1809
          - elixir_version: 1.14.5
            erlang_version: 24.3.4.12
            windows_version: 1809
          - elixir_version: 1.14.5
            erlang_version: 23.3.4.18
            windows_version: 1809
          # Elixir 1.13.4
          - elixir_version: 1.13.4
            erlang_version: 25.3.2.1
            windows_version: 1809
          - elixir_version: 1.13.4
            erlang_version: 25.2.3
            windows_version: 1809
          - elixir_version: 1.13.4
            erlang_version: 25.1.2
            windows_version: 1809
          - elixir_version: 1.13.4
            erlang_version: 25.0.4
            windows_version: 1809
          - elixir_version: 1.13.4
            erlang_version: 24.3.4.12
            windows_version: 1809
          - elixir_version: 1.13.4
            erlang_version: 23.3.4.18
            windows_version: 1809
          - elixir_version: 1.13.4
            erlang_version: 22.3
            windows_version: 1809
          # Erlang 1.12.3
          - elixir_version: 1.12.3
            erlang_version: 24.3.4.12
            windows_version: 1809
          - elixir_version: 1.12.3
            erlang_version: 23.3.4.18
            windows_version: 1809
          - elixir_version: 1.12.3
            erlang_version: 22.3
            windows_version: 1809
          # Erlang 1.11.3
          - elixir_version: 1.12.3
            erlang_version: 24.3.4.12
            windows_version: 1809
          - elixir_version: 1.11.3
            erlang_version: 23.3.4.18
            windows_version: 1809
          - elixir_version: 1.11.3
            erlang_version: 22.3
            windows_version: 1809
          # Erlang 1.10.4
          - elixir_version: 1.10.4
            erlang_version: 23.3.4.18
            windows_version: 1809
          - elixir_version: 1.10.4
            erlang_version: 22.3
            windows_version: 1809
    runs-on: windows-2019
    permissions:
      contents: read
      packages: write
    steps:
      - name: Force build if workflow_dispatch or re-run
        id: force
        if: github.event_name == 'workflow_dispatch' || github.run_attempt != '1'
        run: echo "force=-Force" >> $env:GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build Elixir tag for Docker Hub (if needed)
        run: ./build_elixir_container.ps1 -ImageNameRoot ${{ secrets.DOCKER_USERNAME }}/windows- -WindowsVersion ${{ matrix.windows_version }} -ErlangVersion ${{ matrix.erlang_version }} -ElixirVersion ${{ matrix.elixir_version }} ${{ steps.force.outputs.force }}
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Elixir tag for GHCR (if needed)
        run: ./build_elixir_container.ps1 -ImageNameRoot ${{ env.REGISTRY }}/${{ github.repository_owner }}/windows- -WindowsVersion ${{ matrix.windows_version }} -ErlangVersion ${{ matrix.erlang_version }} -ElixirVersion ${{ matrix.elixir_version }} ${{ steps.force.outputs.force }}
