name: Build Erlang/Elixir images

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build2019:
    continue-on-error: true
    strategy:
      matrix:
        erlang_version: [24.3.4.4, 24.3.4.5, 25.0.4]
        elixir_version: [1.13.4, 1.14.0]
        windows_version: [1809]
    runs-on: windows-2019
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Force build if workflow_dispatch or re-run
        id: force
        if: github.event_name == 'workflow_dispatch' || github.run_attempt != '1'
        run: echo "::set-output name=force::-Force"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Erlang tag (if needed)
        run: ./build_erlang_container.ps1 -ImageNameRoot ${{ secrets.DOCKER_USERNAME }}/windows- -WindowsVersion ${{ matrix.windows_version }} -ErlangVersion ${{ matrix.erlang_version }} ${{ steps.force.outputs.force }}
      - name: Build Elixir tag (if needed)
        run: ./build_elixir_container.ps1 -ImageNameRoot ${{ secrets.DOCKER_USERNAME }}/windows- -WindowsVersion ${{ matrix.windows_version }} -ErlangVersion ${{ matrix.erlang_version }} -ElixirVersion ${{ matrix.elixir_version }} ${{ steps.force.outputs.force }}
