name: CI

on:
  push:
  pull_request:

jobs:
  windows_tests:
    name: Run Windows Tests
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: .\InstallTestDependencies.ps1
      - name: Run tests
        run: .\RunPesterTests.ps1

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      # cache the ASDF directory, using the values from .tool-versions
      - name: ASDF cache
        uses: actions/cache@v3
        with:
          path: ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
        id: asdf-cache
      # only run `asdf install` if we didn't hit the cache
      - uses: asdf-vm/actions/setup@v2
        if: steps.asdf-cache.outputs.cache-hit != 'true'
      - run: asdf plugin-add ansible https://github.com/amrox/asdf-pyapp.git
        env:
          ASDF_PYAPP_INCLUDE_DEPS: 1
        if: steps.asdf-cache.outputs.cache-hit != 'true'
      - uses: asdf-vm/actions/install@v2
        if: steps.asdf-cache.outputs.cache-hit != 'true'

  lint_scripts:
    name: Lint Scripts
    runs-on: ubuntu-latest
    needs: setup
    steps:

      - uses: actions/checkout@v3
      - name: ASDF cache
        uses: actions/cache@v3
        with:
          path: ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
      - uses: mbta/actions/reshim-asdf@v1
      - name: Shellcheck
        run: shellcheck **/*.sh
