---

name: Update version of Command document

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-1
      DOCUMENT_NAME: mbta-pull-ecr-stack-deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - id: update_document
        run: |
          if aws ssm describe-document --name "$DOCUMENT_NAME" >/dev/null 2>&1; then
            aws ssm update-document --name "$DOCUMENT_NAME" --content "file://pull_ecr_stack_deploy.cmd.yml" --document-version "\$LATEST" | tee command-update.json
            echo "document_version=$(jq -r .DocumentDescription.DocumentVersion command-update.json 2>/dev/null)" >> $GITHUB_OUTPUT
          else
            aws ssm create-document --name "$DOCUMENT_NAME" --document-format YAML --document-type Command --content "file://pull_ecr_stack_deploy.cmd.yml"
          fi
      - if: steps.update_document.output.document_version
        run: aws ssm update-document-default-version --name "$DOCUMENT_NAME" --document-version ${{ steps.update_document.outputs.document_version }}
