---

name: vagrant-up

on:
  workflow_dispatch:
  # disabled due to consistent failures on macOS runners
  # https://github.com/actions/runner-images/issues/8730
  # push:
  #   paths:
  #     - linux/**

permissions:
  contents: read # private repo, needs permission to read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vagrant-up:
    name: Run Vagrant Up
    runs-on: macos-latest
    env:
      VAGRANT_HOSTNAME: github
      GITHUB_REPO: ${{ github.repository }}
      GIT_BRANCH: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Cache Vagrant boxes
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: ~/.vagrant.d
          key: ${{ runner.os }}-vagrant-${{ hashFiles('linux/Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Show Vagrant version
        run: vagrant --version
      - name: Install vagrant plugins
        run: |
          vagrant plugin install vagrant-env
          vagrant plugin install vagrant-vbguest
      - name: Run vagrant up
        working-directory: linux
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: vagrant up
      - name: Output Cloud-Init status
        if: ${{ failure() }}
        working-directory: linux
        env:
          ANSIBLE_VAULT_PASSWORD: ignored
        run: vagrant ssh -c 'cat /run/cloud-init/status.json'
      - name: Output Cloud-Init Logs
        if: ${{ failure() }}
        working-directory: linux
        env:
          ANSIBLE_VAULT_PASSWORD: ignored
        run: vagrant ssh -c 'sudo cat /var/log/cloud-init*'
